name: buf
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@f54accd7aea492e583270b09f6543dadf1ab8d96
      # Ensure that `buf` is installed
      - run: buf --version
